########
GET http://localhost:5000/test/64524121806a7b42422e4fa2

########
POST http://localhost:5000/login
Content-Type:  application/json

{
    "email":"2@example.com",
    "password":"password123"
}

######
POST http://localhost:5000/register
Content-Type:  application/json

{
    "email":"elad12345@example.com",
    "gamertag":"elad12345",
    "password":"password12",
    "gender":"male",
    "dob":"1994-12-24T00:00:00.000Z",
    "g1":"0",
    "g2":"EUW",
    "g3":"ARAM",
    "g4":"Top",
    "g5":"Diamond I",
    "discord":"elaad",
    "country":"France",
    "language":"French",
    "picture":" "
}

########
GET http://localhost:5000/homepage/64524121806a7b42422e4fa1
